class XTSN:
	def __init__(self, crypt: bytes, tweak: bytes): ...

	def decrypt(self, buf: bytes, sector_offset: int, sector_size: int = 0x200,
		skipped_bytes: int = 0) -> bytes: ...

	def encrypt(self, buf: bytes, sector_offset: int, sector_size: int = 0x200,
		skipped_bytes: int = 0) -> bytes: ...
