def _xtsn_schedule(key: bytes, tweak: bytes) -> bytes: ...

def _xtsn_decrypt(buf: bytes, roundkeys_x2: bytes, sector_offset_hi: int, sector_offset_lo: int,
                  sector_size: int, skipped_bytes: int) -> bytes: ...

def _xtsn_encrypt(buf: bytes, roundkeys_x2: bytes, sector_offset_hi: int, sector_offset_lo: int,
                  sector_size: int, skipped_bytes: int) -> bytes: ...
